import type { ActivityItem, Lead, Territory, ToolItem } from "./types";

export const leads: Lead[] = [
  {
    id: "ld-001",
    company: "Summit Ridge Dental",
    niche: "Dental",
    city: "Austin",
    state: "TX",
    status: "Demo Scheduled",
    exclusiveStatus: "Pending Lock",
    contactName: "Dr. Melissa Hart",
    phone: "(512) 555-0148",
    email: "melissa@summitridgedental.com",
    website: "summitridgedental.com",
    competitors: ["Austin Smile Bar", "Riverside Family Dental"],
    notes:
      "Very interested in AI Overview visibility — currently invisible on ChatGPT and Perplexity for 'best dentist Austin'. Wants to see competitor gap report before demo.",
    lastContact: "2026-08-10",
    dealValue: 2400,
    source: "Cold Outbound",
    avatarAccent: "blue",
  },
  {
    id: "ld-002",
    company: "Bluewater Roofing Co.",
    niche: "Roofing",
    city: "Tampa",
    state: "FL",
    status: "Negotiating",
    exclusiveStatus: "Pending Lock",
    contactName: "Jake Coronado",
    phone: "(813) 555-0192",
    email: "jake@bluewaterroofing.com",
    website: "bluewaterroofing.com",
    competitors: ["Gulf Coast Roofing", "StormShield Roofers"],
    notes:
      "Owner wants exclusivity locked before storm season. Comparing us against a local SEO shop — emphasize AI answer citations vs. traditional rankings.",
    lastContact: "2026-08-11",
    dealValue: 3200,
    source: "Referral",
    avatarAccent: "violet",
  },
  {
    id: "ld-003",
    company: "Prime Legal Partners",
    niche: "Personal Injury Law",
    city: "Chicago",
    state: "IL",
    status: "Closed Won",
    exclusiveStatus: "Exclusive Locked",
    contactName: "Andrea Weiss",
    phone: "(312) 555-0110",
    email: "aweiss@primelegalpartners.com",
    website: "primelegalpartners.com",
    competitors: ["Chicago Injury Group", "Midwest Trial Lawyers"],
    notes:
      "Signed 12-month exclusive contract. Onboarding kicked off — pitch pack and citation audit delivered.",
    lastContact: "2026-08-05",
    dealValue: 5000,
    source: "Inbound",
    avatarAccent: "emerald",
  },
  {
    id: "ld-004",
    company: "Coastal HVAC Solutions",
    niche: "HVAC",
    city: "San Diego",
    state: "CA",
    status: "Contacted",
    exclusiveStatus: "Available",
    contactName: "Rick Alvarado",
    phone: "(619) 555-0173",
    email: "rick@coastalhvacsd.com",
    website: "coastalhvacsd.com",
    competitors: ["SD Comfort Systems", "Pacific Air Pros"],
    notes: "Left voicemail, sent follow-up email with sample GEO audit. Awaiting response.",
    lastContact: "2026-08-08",
    dealValue: 1800,
    source: "Cold Outbound",
    avatarAccent: "cyan",
  },
  {
    id: "ld-005",
    company: "Golden State Med Spa",
    niche: "Medical Spa",
    city: "Sacramento",
    state: "CA",
    status: "New",
    exclusiveStatus: "Available",
    contactName: "Priya Nair",
    phone: "(916) 555-0121",
    email: "priya@goldenstatemedspa.com",
    website: "goldenstatemedspa.com",
    competitors: ["Radiance Med Spa", "Luxe Aesthetics Sacramento"],
    notes: "Inbound form fill from the AI visibility checker tool. Not yet contacted.",
    lastContact: "2026-08-12",
    dealValue: 2100,
    source: "Website Tool",
    avatarAccent: "rose",
  },
  {
    id: "ld-006",
    company: "Ironclad Auto Repair",
    niche: "Auto Repair",
    city: "Denver",
    state: "CO",
    status: "Demo Scheduled",
    exclusiveStatus: "Pending Lock",
    contactName: "Tom Baxter",
    phone: "(303) 555-0165",
    email: "tom@ironcladauto.com",
    website: "ironcladauto.com",
    competitors: ["Mile High Auto Care", "Denver Precision Motors"],
    notes: "Demo booked for Thursday 2pm MT. Send calendar invite + prep one-pager.",
    lastContact: "2026-08-09",
    dealValue: 1600,
    source: "Referral",
    avatarAccent: "amber",
  },
  {
    id: "ld-007",
    company: "Harborview Orthodontics",
    niche: "Orthodontics",
    city: "Seattle",
    state: "WA",
    status: "Negotiating",
    exclusiveStatus: "Pending Lock",
    contactName: "Dr. Wesley Chan",
    phone: "(206) 555-0187",
    email: "wchan@harborvieworthodontics.com",
    website: "harborvieworthodontics.com",
    competitors: ["Emerald City Orthodontics", "Seattle Smile Design"],
    notes: "Reviewing contract redlines with their office manager. Expected close this week.",
    lastContact: "2026-08-11",
    dealValue: 2800,
    source: "Inbound",
    avatarAccent: "blue",
  },
  {
    id: "ld-008",
    company: "Apex Roofing & Restoration",
    niche: "Roofing",
    city: "Oklahoma City",
    state: "OK",
    status: "Closed Lost",
    exclusiveStatus: "Available",
    contactName: "Marcus Doyle",
    phone: "(405) 555-0134",
    email: "marcus@apexroofingok.com",
    website: "apexroofingok.com",
    competitors: ["OKC Roofing Pros", "Sooner State Roofing"],
    notes: "Went with an in-house marketing hire instead. Revisit in Q1 next year.",
    lastContact: "2026-07-28",
    dealValue: 0,
    source: "Cold Outbound",
    avatarAccent: "rose",
  },
  {
    id: "ld-009",
    company: "Willow Creek Family Law",
    niche: "Family Law",
    city: "Nashville",
    state: "TN",
    status: "Contacted",
    exclusiveStatus: "Available",
    contactName: "Renee Osei",
    phone: "(615) 555-0199",
    email: "renee@willowcreekfamilylaw.com",
    website: "willowcreekfamilylaw.com",
    competitors: ["Nashville Family Legal Group", "Southern Custody Law"],
    notes: "Sent GEO visibility snapshot. She wants case studies from other law firms before proceeding.",
    lastContact: "2026-08-07",
    dealValue: 2600,
    source: "LinkedIn",
    avatarAccent: "violet",
  },
  {
    id: "ld-010",
    company: "Northgate Veterinary Hospital",
    niche: "Veterinary",
    city: "Minneapolis",
    state: "MN",
    status: "Demo Scheduled",
    exclusiveStatus: "Available",
    contactName: "Dr. Kevin Ostrom",
    phone: "(612) 555-0142",
    email: "kevin@northgatevet.com",
    website: "northgatevet.com",
    competitors: ["Twin Cities Animal Hospital", "Lakeside Vet Care"],
    notes: "Demo confirmed for next Monday. Wants ROI projection tied to new client bookings.",
    lastContact: "2026-08-10",
    dealValue: 1900,
    source: "Referral",
    avatarAccent: "cyan",
  },
  {
    id: "ld-011",
    company: "Precision Plumbing Group",
    niche: "Plumbing",
    city: "Phoenix",
    state: "AZ",
    status: "New",
    exclusiveStatus: "Available",
    contactName: "Diego Fuentes",
    phone: "(602) 555-0176",
    email: "diego@precisionplumbingaz.com",
    website: "precisionplumbingaz.com",
    competitors: ["Valley Plumbing Experts", "Desert Rooter & Plumbing"],
    notes: "Just submitted intake form after seeing a competitor's citation on Perplexity.",
    lastContact: "2026-08-12",
    dealValue: 1500,
    source: "Website Tool",
    avatarAccent: "amber",
  },
  {
    id: "ld-012",
    company: "Elevate Physical Therapy",
    niche: "Physical Therapy",
    city: "Charlotte",
    state: "NC",
    status: "Closed Won",
    exclusiveStatus: "Exclusive Locked",
    contactName: "Dr. Sarah Lindqvist",
    phone: "(704) 555-0158",
    email: "sarah@elevatept.com",
    website: "elevatept.com",
    competitors: ["Charlotte Motion PT", "Queen City Rehab"],
    notes: "Closed on annual plan with quarterly QBRs. First AI citation audit delivered.",
    lastContact: "2026-08-01",
    dealValue: 2200,
    source: "Inbound",
    avatarAccent: "emerald",
  },
  {
    id: "ld-013",
    company: "Cascade Roofing & Solar",
    niche: "Roofing",
    city: "Portland",
    state: "OR",
    status: "Negotiating",
    exclusiveStatus: "Pending Lock",
    contactName: "Nate Forsythe",
    phone: "(503) 555-0163",
    email: "nate@cascaderoofingsolar.com",
    website: "cascaderoofingsolar.com",
    competitors: ["Rose City Roofing", "PNW Solar Roofers"],
    notes: "Comparing our exclusive territory lock against two other GEO vendors. Price sensitive.",
    lastContact: "2026-08-06",
    dealValue: 2900,
    source: "Cold Outbound",
    avatarAccent: "blue",
  },
  {
    id: "ld-014",
    company: "Brightline Med Spa & Wellness",
    niche: "Medical Spa",
    city: "Miami",
    state: "FL",
    status: "Contacted",
    exclusiveStatus: "Pending Lock",
    contactName: "Isabela Cruz",
    phone: "(305) 555-0129",
    email: "isabela@brightlinemedspa.com",
    website: "brightlinemedspa.com",
    competitors: ["Miami Glow Aesthetics", "South Beach Wellness Studio"],
    notes: "High intent — asked directly about locking exclusivity for Miami med spa niche.",
    lastContact: "2026-08-09",
    dealValue: 3400,
    source: "Referral",
    avatarAccent: "rose",
  },
  {
    id: "ld-015",
    company: "Redstone Personal Injury Law",
    niche: "Personal Injury Law",
    city: "Phoenix",
    state: "AZ",
    status: "Demo Scheduled",
    exclusiveStatus: "Pending Lock",
    contactName: "Charles Ibbotson",
    phone: "(602) 555-0184",
    email: "charles@redstoneinjurylaw.com",
    website: "redstoneinjurylaw.com",
    competitors: ["Phoenix Trial Attorneys", "Desert Justice Law"],
    notes: "Managing partner will attend demo personally. High-value niche, prioritize prep.",
    lastContact: "2026-08-11",
    dealValue: 4800,
    source: "Inbound",
    avatarAccent: "violet",
  },
  {
    id: "ld-016",
    company: "TrueNorth HVAC & Electrical",
    niche: "HVAC",
    city: "Minneapolis",
    state: "MN",
    status: "New",
    exclusiveStatus: "Available",
    contactName: "Erik Solheim",
    phone: "(612) 555-0198",
    email: "erik@truenorthhvac.com",
    website: "truenorthhvac.com",
    competitors: ["Northland Air Systems", "Twin Cities Comfort Co."],
    notes: "Downloaded the AI visibility checklist PDF. No call yet.",
    lastContact: "2026-08-12",
    dealValue: 1700,
    source: "Website Tool",
    avatarAccent: "cyan",
  },
  {
    id: "ld-017",
    company: "Lakeshore Orthodontic Studio",
    niche: "Orthodontics",
    city: "Cleveland",
    state: "OH",
    status: "Contacted",
    exclusiveStatus: "Available",
    contactName: "Dr. Nina Popescu",
    phone: "(216) 555-0117",
    email: "nina@lakeshoreortho.com",
    website: "lakeshoreortho.com",
    competitors: ["Cleveland Clear Smiles", "North Coast Orthodontics"],
    notes: "Second call scheduled after she reviewed the competitor GEO gap report.",
    lastContact: "2026-08-08",
    dealValue: 2300,
    source: "Cold Outbound",
    avatarAccent: "amber",
  },
  {
    id: "ld-018",
    company: "Vantage Auto Collision",
    niche: "Auto Repair",
    city: "Tampa",
    state: "FL",
    status: "Closed Lost",
    exclusiveStatus: "Available",
    contactName: "Louis Ferreira",
    phone: "(813) 555-0141",
    email: "louis@vantagecollision.com",
    website: "vantagecollision.com",
    competitors: ["Tampa Bay Body Works", "Suncoast Collision Center"],
    notes: "Budget got cut this quarter. Follow up in 90 days.",
    lastContact: "2026-07-22",
    dealValue: 0,
    source: "Referral",
    avatarAccent: "rose",
  },
];

export const territories: Territory[] = [
  {
    id: "tr-001",
    niche: "Personal Injury Law",
    city: "Chicago",
    state: "IL",
    status: "Locked",
    lockedBy: "Prime Legal Partners",
    lockedSince: "2026-06-15",
    monthlyValue: 5000,
    population: "2.7M",
    competitionLevel: "High",
  },
  {
    id: "tr-002",
    niche: "Physical Therapy",
    city: "Charlotte",
    state: "NC",
    status: "Locked",
    lockedBy: "Elevate Physical Therapy",
    lockedSince: "2026-07-01",
    monthlyValue: 2200,
    population: "890K",
    competitionLevel: "Medium",
  },
  {
    id: "tr-003",
    niche: "Roofing",
    city: "Tampa",
    state: "FL",
    status: "Reserved",
    lockedBy: "Bluewater Roofing Co.",
    lockedSince: "2026-08-11",
    monthlyValue: 3200,
    population: "400K",
    competitionLevel: "High",
  },
  {
    id: "tr-004",
    niche: "Dental",
    city: "Austin",
    state: "TX",
    status: "Reserved",
    lockedBy: "Summit Ridge Dental",
    lockedSince: "2026-08-10",
    monthlyValue: 2400,
    population: "980K",
    competitionLevel: "High",
  },
  {
    id: "tr-005",
    niche: "HVAC",
    city: "San Diego",
    state: "CA",
    status: "Available",
    population: "1.4M",
    competitionLevel: "Medium",
  },
  {
    id: "tr-006",
    niche: "Medical Spa",
    city: "Sacramento",
    state: "CA",
    status: "Available",
    population: "525K",
    competitionLevel: "Low",
  },
  {
    id: "tr-007",
    niche: "Auto Repair",
    city: "Denver",
    state: "CO",
    status: "Reserved",
    lockedBy: "Ironclad Auto Repair",
    lockedSince: "2026-08-09",
    monthlyValue: 1600,
    population: "715K",
    competitionLevel: "Medium",
  },
  {
    id: "tr-008",
    niche: "Orthodontics",
    city: "Seattle",
    state: "WA",
    status: "Reserved",
    lockedBy: "Harborview Orthodontics",
    lockedSince: "2026-08-01",
    monthlyValue: 2800,
    population: "740K",
    competitionLevel: "High",
  },
  {
    id: "tr-009",
    niche: "Roofing",
    city: "Oklahoma City",
    state: "OK",
    status: "Available",
    population: "690K",
    competitionLevel: "Low",
  },
  {
    id: "tr-010",
    niche: "Family Law",
    city: "Nashville",
    state: "TN",
    status: "Available",
    population: "690K",
    competitionLevel: "Medium",
  },
  {
    id: "tr-011",
    niche: "Veterinary",
    city: "Minneapolis",
    state: "MN",
    status: "Available",
    population: "430K",
    competitionLevel: "Low",
  },
  {
    id: "tr-012",
    niche: "Plumbing",
    city: "Phoenix",
    state: "AZ",
    status: "Available",
    population: "1.7M",
    competitionLevel: "Medium",
  },
  {
    id: "tr-013",
    niche: "Roofing",
    city: "Portland",
    state: "OR",
    status: "Reserved",
    lockedBy: "Cascade Roofing & Solar",
    lockedSince: "2026-08-06",
    monthlyValue: 2900,
    population: "650K",
    competitionLevel: "Medium",
  },
  {
    id: "tr-014",
    niche: "Medical Spa",
    city: "Miami",
    state: "FL",
    status: "Reserved",
    lockedBy: "Brightline Med Spa & Wellness",
    lockedSince: "2026-08-09",
    monthlyValue: 3400,
    population: "460K",
    competitionLevel: "High",
  },
  {
    id: "tr-015",
    niche: "Personal Injury Law",
    city: "Phoenix",
    state: "AZ",
    status: "Reserved",
    lockedBy: "Redstone Personal Injury Law",
    lockedSince: "2026-08-11",
    monthlyValue: 4800,
    population: "1.7M",
    competitionLevel: "High",
  },
  {
    id: "tr-016",
    niche: "Orthodontics",
    city: "Cleveland",
    state: "OH",
    status: "Available",
    population: "370K",
    competitionLevel: "Low",
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "ac-001",
    type: "demo",
    title: "Demo scheduled",
    description: "Booked GEO visibility demo for Thursday 2:00 PM MT.",
    timestamp: "2026-08-12T14:20:00Z",
    leadCompany: "Ironclad Auto Repair",
  },
  {
    id: "ac-002",
    type: "territory",
    title: "Territory reserved",
    description: "Miami · Medical Spa placed on 48-hour hold pending signature.",
    timestamp: "2026-08-12T12:05:00Z",
    leadCompany: "Brightline Med Spa & Wellness",
  },
  {
    id: "ac-003",
    type: "email",
    title: "Follow-up sent",
    description: "Sent AI visibility checklist PDF after inbound tool signup.",
    timestamp: "2026-08-12T09:40:00Z",
    leadCompany: "TrueNorth HVAC & Electrical",
  },
  {
    id: "ac-004",
    type: "contract",
    title: "Contract redlines received",
    description: "Office manager returned markup on the exclusivity clause.",
    timestamp: "2026-08-11T21:15:00Z",
    leadCompany: "Harborview Orthodontics",
  },
  {
    id: "ac-005",
    type: "call",
    title: "Discovery call completed",
    description: "32-minute call covering current AI Overview presence and competitor gaps.",
    timestamp: "2026-08-11T18:30:00Z",
    leadCompany: "Bluewater Roofing Co.",
  },
  {
    id: "ac-006",
    type: "status",
    title: "Status moved to Closed Won",
    description: "12-month exclusive agreement signed and countersigned.",
    timestamp: "2026-08-11T16:00:00Z",
    leadCompany: "Prime Legal Partners",
  },
  {
    id: "ac-007",
    type: "note",
    title: "Note added",
    description: "Managing partner will personally attend the demo — prioritize prep deck.",
    timestamp: "2026-08-11T11:20:00Z",
    leadCompany: "Redstone Personal Injury Law",
  },
  {
    id: "ac-008",
    type: "email",
    title: "Case studies requested",
    description: "Asked for law-firm specific case studies before moving forward.",
    timestamp: "2026-08-10T20:05:00Z",
    leadCompany: "Willow Creek Family Law",
  },
];

export const tools: ToolItem[] = [
  {
    id: "tl-001",
    name: "Pitch Pack Generator",
    description:
      "Auto-generate a branded, niche-specific pitch deck with live AI visibility gap data for any lead.",
    icon: "Presentation",
    accent: "blue",
    status: "active",
    href: "/tools/pitch-pack-generator",
  },
  {
    id: "tl-002",
    name: "Contract Generator",
    description:
      "Draft exclusivity agreements and service contracts pre-filled with territory and pricing terms.",
    icon: "FileSignature",
    accent: "violet",
    status: "active",
    href: "/tools/contract-generator",
  },
  {
    id: "tl-003",
    name: "AI Visibility Scanner",
    description:
      "Scan ChatGPT, Perplexity, and Google AI Overviews for brand citations against competitors.",
    icon: "ScanSearch",
    accent: "cyan",
    status: "active",
    href: "/tools/visibility-scanner",
  },
  {
    id: "tl-004",
    name: "Territory Locker",
    description:
      "Reserve and manage exclusive niche + city territories with automatic conflict checks.",
    icon: "MapPinned",
    accent: "emerald",
    status: "active",
    href: "/territories",
  },
  {
    id: "tl-005",
    name: "ROI Calculator",
    description:
      "Model projected new-client revenue from improved AI answer citations for prospects.",
    icon: "Calculator",
    accent: "amber",
    status: "coming-soon",
    href: "/tools/roi-calculator",
  },
  {
    id: "tl-006",
    name: "Outreach Sequencer",
    description:
      "Build multi-touch cold outbound sequences personalized with each lead's GEO gap report.",
    icon: "Send",
    accent: "rose",
    status: "coming-soon",
    href: "/tools/outreach-sequencer",
  },
];
