from __future__ import annotations

import os
import re
import sys
from collections.abc import Sequence
from pathlib import Path

from .config import (
    _FUNCTION_CALL_PATTERN,
    _IMPORT_PATTERNS,
    CODE_EXTENSIONS,
    IGNORED_FILENAMES,
    MAX_CHUNK_TOKEN_ESTIMATE,
    MAX_CHUNK_WORDS,
    MIN_CHUNK_WORDS,
    TEXT_EXTENSIONS,
)

IGNORED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    "coverage",
    "__pycache__",
    ".next",
    ".idea",
    ".vscode",
}

NOISE_PATTERNS = [
    re.compile(r"^\s*$"),
    re.compile(r"^\s*Table of Contents\s*$", re.IGNORECASE),
    re.compile(r"^\s*Copyright\s+\(c\)\s+\d{4}", re.IGNORECASE),
    re.compile(r"^\s*All rights reserved\.?\s*$", re.IGNORECASE),
    re.compile(r"^\s*Generated by\s+", re.IGNORECASE),
]

_CODE_BOUNDARY_PATTERNS: dict[str, re.Pattern[str]] = {
    ".py": re.compile(r"^(?:class\s+\w|def\s+\w|async\s+def\s+\w|@\w+)", re.MULTILINE),
    ".js": re.compile(
        r"^(?:(?:export\s+)?(?:(?:async\s+)?function\s+\w|class\s+\w|const\s+\w+\s*=\s*(?:async\s+)?\(|module\.exports))",
        re.MULTILINE,
    ),
    ".ts": re.compile(
        r"^(?:(?:export\s+)?(?:(?:async\s+)?function\s+\w|class\s+\w|interface\s+\w|type\s+\w|const\s+\w+\s*=\s*(?:async\s+)?\())",
        re.MULTILINE,
    ),
    ".tsx": re.compile(
        r"^(?:(?:export\s+)?(?:(?:async\s+)?function\s+\w|class\s+\w|interface\s+\w|type\s+\w|const\s+\w+\s*=))",
        re.MULTILINE,
    ),
    ".jsx": re.compile(
        r"^(?:(?:export\s+)?(?:(?:async\s+)?function\s+\w|class\s+\w|const\s+\w+\s*=))",
        re.MULTILINE,
    ),
    ".java": re.compile(
        r"^(?:\s*(?:public|private|protected|static|abstract|final)\s+.*(?:class\s+\w|interface\s+\w|\w+\s*\())",
        re.MULTILINE,
    ),
    ".kt": re.compile(
        r"^(?:\s*(?:fun\s+|class\s+|interface\s+|object\s+|data\s+class\s+))", re.MULTILINE
    ),
    ".go": re.compile(r"^(?:func\s+|type\s+\w+\s+(?:struct|interface))", re.MULTILINE),
    ".rs": re.compile(
        r"^(?:(?:pub\s+)?(?:fn\s+|struct\s+|enum\s+|impl\s+|trait\s+|mod\s+))", re.MULTILINE
    ),
    ".c": re.compile(r"^(?:\w[\w\s\*]+\s+\w+\s*\(|typedef\s+|struct\s+\w+)", re.MULTILINE),
    ".h": re.compile(
        r"^(?:\w[\w\s\*]+\s+\w+\s*\(|typedef\s+|struct\s+\w+|#define\s+\w+)", re.MULTILINE
    ),
    ".cpp": re.compile(
        r"^(?:\w[\w\s\*:&]+\s+\w+\s*\(|class\s+\w+|namespace\s+\w+|template)", re.MULTILINE
    ),
    ".cs": re.compile(
        r"^(?:\s*(?:public|private|protected|internal|static|abstract)\s+.*(?:class\s+\w|interface\s+\w|\w+\s*\())",
        re.MULTILINE,
    ),
    ".php": re.compile(
        r"^(?:\s*(?:public|private|protected|static)?\s*function\s+\w|class\s+\w)", re.MULTILINE
    ),
    ".rb": re.compile(r"^(?:def\s+\w|class\s+\w|module\s+\w)", re.MULTILINE),
    ".swift": re.compile(
        r"^(?:\s*(?:func\s+|class\s+|struct\s+|enum\s+|protocol\s+|extension\s+))", re.MULTILINE
    ),
}

# Tree-sitter language mapping: extension -> (language_name, grammar_package_name)
_TREE_SITTER_LANGUAGES: dict[str, tuple[str, str]] = {
    ".py": ("python", "tree_sitter_python"),
    ".js": ("javascript", "tree_sitter_javascript"),
    ".ts": ("typescript", "tree_sitter_typescript"),
    ".tsx": ("tsx", "tree_sitter_typescript"),
    ".jsx": ("javascript", "tree_sitter_javascript"),
    ".java": ("java", "tree_sitter_java"),
    ".go": ("go", "tree_sitter_go"),
    ".rs": ("rust", "tree_sitter_rust"),
    ".c": ("c", "tree_sitter_c"),
    ".h": ("c", "tree_sitter_c"),
    ".cpp": ("cpp", "tree_sitter_cpp"),
    ".rb": ("ruby", "tree_sitter_ruby"),
}

# AST node types that represent top-level semantic boundaries
_AST_BOUNDARY_NODE_TYPES: dict[str, set[str]] = {
    "python": {
        "function_definition",
        "async_function_definition",
        "class_definition",
        "decorated_definition",
    },
    "javascript": {
        "function_declaration",
        "class_declaration",
        "method_definition",
        "arrow_function",
        "export_statement",
    },
    "typescript": {
        "function_declaration",
        "class_declaration",
        "method_definition",
        "interface_declaration",
        "type_alias_declaration",
        "export_statement",
    },
    "tsx": {
        "function_declaration",
        "class_declaration",
        "method_definition",
        "interface_declaration",
        "type_alias_declaration",
        "export_statement",
    },
    "java": {
        "class_declaration",
        "interface_declaration",
        "method_declaration",
        "constructor_declaration",
    },
    "go": {"function_declaration", "method_declaration", "type_declaration"},
    "rust": {"function_item", "impl_item", "struct_item", "enum_item", "trait_item", "mod_item"},
    "c": {"function_definition", "struct_specifier", "type_definition"},
    "cpp": {"function_definition", "class_specifier", "struct_specifier", "namespace_definition"},
    "ruby": {"method", "class", "module", "singleton_method"},
}

# Cached tree-sitter parsers
_TREE_SITTER_PARSER_CACHE: dict[str, object] = {}
_TREE_SITTER_AVAILABLE: bool | None = None

MAX_FILE_SIZE_BYTES = 512 * 1024  # 512 KB — skip files larger than this
_MINIFIED_PATTERN = re.compile(r"[^\n]{500,}")  # lines >500 chars suggest minification


def estimate_tokens(text: str) -> int:
    return max(1, int(len(text.split()) * 1.3))


def tokenize(text: str) -> list[str]:
    return re.findall(r"[a-zA-Z0-9_]+", text.lower())


def char_ngrams(token: str, n: int = 3) -> list[str]:
    padded = f"^{token}$"
    if len(padded) < n:
        return [padded]
    return [padded[i : i + n] for i in range(0, len(padded) - n + 1)]


def clean_text(text: str) -> str:
    cleaned_lines: list[str] = []
    seen_recent: set[str] = set()

    for raw_line in text.splitlines():
        line = re.sub(r"\s+", " ", raw_line.strip())
        if any(pattern.match(line) for pattern in NOISE_PATTERNS):
            continue
        if len(line) < 2:
            continue
        lowered = line.lower()
        if lowered in seen_recent:
            continue
        if len(seen_recent) > 5000:
            seen_recent.clear()
        seen_recent.add(lowered)
        cleaned_lines.append(line)

    return "\n".join(cleaned_lines).strip()


def chunk_text(text: str, chunk_size_words: int, overlap_words: int) -> list[str]:
    lines = text.splitlines()
    if not lines:
        return []

    chunks: list[str] = []
    cursor = 0

    while cursor < len(lines):
        current: list[str] = []
        words_in_chunk = 0
        end = cursor

        while end < len(lines):
            line = lines[end]
            line_words = max(1, len(line.split()))
            if current and words_in_chunk + line_words > chunk_size_words:
                break
            current.append(line)
            words_in_chunk += line_words
            end += 1

        chunk = "\n".join(current).strip()
        if chunk:
            chunks.append(chunk)

        if end >= len(lines):
            break

        rewind_words = 0
        rewind_cursor = end - 1
        while rewind_cursor >= cursor and rewind_words < overlap_words:
            rewind_words += max(1, len(lines[rewind_cursor].split()))
            rewind_cursor -= 1

        next_cursor = max(cursor + 1, rewind_cursor + 1)
        cursor = next_cursor

    return chunks


def is_code_file(path: str) -> bool:
    return Path(path).suffix.lower() in CODE_EXTENSIONS


def chunk_code(text: str, source: str, chunk_size_words: int) -> list[str]:
    """Split code by function/class boundaries using AST parsing when available.

    Uses tree-sitter for true semantic AST chunking when available.
    Falls back to regex-based chunking, then to standard chunk_text() if
    no language pattern matches or if the file has no recognizable boundaries.
    """
    ext = Path(source).suffix.lower()

    # Try AST-based chunking first (when tree-sitter is available)
    if _is_tree_sitter_available() and ext in _TREE_SITTER_LANGUAGES:
        ast_chunks = _extract_ast_chunks(text, ext, chunk_size_words)
        if ast_chunks:
            return ast_chunks

    # Fall back to regex-based chunking
    pattern = _CODE_BOUNDARY_PATTERNS.get(ext)
    if pattern is None:
        return chunk_text(text, chunk_size_words, overlap_words=0)

    lines = text.splitlines(keepends=True)
    if not lines:
        return []

    # Find line indices where a new top-level symbol starts
    boundary_lines: list[int] = []
    for i, line in enumerate(lines):
        if pattern.match(line):
            boundary_lines.append(i)

    if not boundary_lines:
        return chunk_text(text, chunk_size_words, overlap_words=0)

    # Build segments between boundaries
    segments: list[str] = []
    if boundary_lines[0] > 0:
        preamble = "".join(lines[: boundary_lines[0]]).strip()
        if preamble:
            segments.append(preamble)

    for idx, start in enumerate(boundary_lines):
        end = boundary_lines[idx + 1] if idx + 1 < len(boundary_lines) else len(lines)
        segment = "".join(lines[start:end]).strip()
        if segment:
            segments.append(segment)

    # Merge small segments or split oversized ones
    chunks: list[str] = []
    buffer: list[str] = []
    buffer_words = 0
    max_words = max(chunk_size_words, MIN_CHUNK_WORDS)

    for segment in segments:
        seg_words = len(segment.split())
        if seg_words > max_words * 2:
            # Flush buffer first
            if buffer:
                chunks.append("\n\n".join(buffer))
                buffer, buffer_words = [], 0
            # Split oversized segment with plain chunker (no overlap for code)
            sub_chunks = chunk_text(segment, chunk_size_words, overlap_words=0)
            chunks.extend(sub_chunks)
        elif buffer_words + seg_words > max_words and buffer:
            chunks.append("\n\n".join(buffer))
            buffer, buffer_words = [segment], seg_words
        else:
            buffer.append(segment)
            buffer_words += seg_words

    if buffer:
        chunks.append("\n\n".join(buffer))

    return [c for c in chunks if c.strip()]


def normalize_chunking(chunk_size_words: int, overlap_words: int) -> tuple[int, int]:
    normalized_chunk = chunk_size_words
    normalized_overlap = overlap_words

    if normalized_chunk < MIN_CHUNK_WORDS:
        print(
            f"[warn] chunk-size {normalized_chunk} too small; raised to {MIN_CHUNK_WORDS} words (~{estimate_tokens('x ' * MIN_CHUNK_WORDS)} token-est).",
            file=sys.stderr,
        )
        normalized_chunk = MIN_CHUNK_WORDS

    if normalized_chunk > MAX_CHUNK_WORDS:
        print(
            f"[warn] chunk-size {normalized_chunk} too large; capped at {MAX_CHUNK_WORDS} words (~{MAX_CHUNK_TOKEN_ESTIMATE} token-est).",
            file=sys.stderr,
        )
        normalized_chunk = MAX_CHUNK_WORDS

    max_overlap = max(20, int(normalized_chunk * 0.45))
    if normalized_overlap >= normalized_chunk:
        normalized_overlap = max(20, int(normalized_chunk * 0.2))
        print(
            f"[warn] overlap must be smaller than chunk-size; adjusted to {normalized_overlap} words.",
            file=sys.stderr,
        )
    elif normalized_overlap > max_overlap:
        print(
            f"[warn] overlap {normalized_overlap} too high; capped at {max_overlap} words.",
            file=sys.stderr,
        )
        normalized_overlap = max_overlap

    return normalized_chunk, normalized_overlap


def is_text_file(path: Path) -> bool:
    return path.suffix.lower() in TEXT_EXTENSIONS


def should_skip_file(path: Path) -> bool:
    """Return True for autogenerated, minified, or token-dense files that add noise."""
    name = path.name.lower()
    if name in IGNORED_FILENAMES:
        return True
    # Block common autogenerated/bundled patterns
    if name.endswith(".min.js") or name.endswith(".min.css"):
        return True
    if name.endswith(".bundle.js") or name.endswith(".chunk.js"):
        return True
    if name.endswith(".map"):  # source maps
        return True
    # SVG files often contain massive path data
    if path.suffix.lower() == ".svg":
        return True
    # Skip oversized files
    try:
        if path.stat().st_size > MAX_FILE_SIZE_BYTES:
            print(
                f"[skip] File too large ({path.stat().st_size} bytes): {path.name}", file=sys.stderr
            )
            return True
    except OSError:
        return True
    return False


def is_minified(text: str, sample_lines: int = 10) -> bool:
    """Detect minified content by checking for extremely long lines."""
    for i, line in enumerate(text.splitlines()):
        if i >= sample_lines:
            break
        if len(line) > 500:
            return True
    return False


def collect_input_files(inputs: Sequence[str]) -> list[Path]:
    files: set[Path] = set()

    for raw in inputs:
        path = Path(raw).expanduser().resolve()
        if not path.exists():
            print(f"[warn] Path does not exist: {path}", file=sys.stderr)
            continue

        if path.is_file():
            if is_text_file(path) and not should_skip_file(path):
                files.add(path)
            continue

        for root, dirs, names in os.walk(path):
            dirs[:] = [d for d in dirs if d not in IGNORED_DIRS]
            for name in names:
                candidate = Path(root) / name
                if is_text_file(candidate) and not should_skip_file(candidate):
                    files.add(candidate.resolve())

    return sorted(files)


def read_text_file(path: Path) -> str | None:
    for encoding in ("utf-8", "utf-16", "latin-1"):
        try:
            return path.read_text(encoding=encoding)
        except UnicodeDecodeError:
            continue
        except OSError:
            return None
    return None


def _is_tree_sitter_available() -> bool:
    """Check if tree-sitter is available and working."""
    global _TREE_SITTER_AVAILABLE
    if _TREE_SITTER_AVAILABLE is not None:
        return _TREE_SITTER_AVAILABLE
    try:
        import tree_sitter  # type: ignore  # noqa: F401

        _TREE_SITTER_AVAILABLE = True
    except ImportError:
        _TREE_SITTER_AVAILABLE = False
    return _TREE_SITTER_AVAILABLE


def _get_tree_sitter_parser(ext: str) -> object | None:
    """Get or create a tree-sitter parser for the given file extension."""
    if ext not in _TREE_SITTER_LANGUAGES:
        return None
    if ext in _TREE_SITTER_PARSER_CACHE:
        return _TREE_SITTER_PARSER_CACHE[ext]

    lang_name, grammar_module = _TREE_SITTER_LANGUAGES[ext]

    try:
        import importlib

        import tree_sitter  # type: ignore

        grammar = importlib.import_module(grammar_module)

        # Handle typescript/tsx which have multiple languages in one package
        if lang_name == "typescript":
            language = tree_sitter.Language(grammar.language_typescript())
        elif lang_name == "tsx":
            language = tree_sitter.Language(grammar.language_tsx())
        else:
            language = tree_sitter.Language(grammar.language())

        parser = tree_sitter.Parser(language)
        _TREE_SITTER_PARSER_CACHE[ext] = parser
        return parser
    except Exception:
        return None


def _extract_ast_chunks(text: str, ext: str, chunk_size_words: int) -> list[str] | None:
    """Extract semantic chunks from code using tree-sitter AST parsing.

    Returns None if tree-sitter parsing fails or is unavailable, allowing
    fallback to regex-based chunking.
    """
    if not _is_tree_sitter_available():
        return None

    parser = _get_tree_sitter_parser(ext)
    if parser is None:
        return None

    lang_name = _TREE_SITTER_LANGUAGES.get(ext, (None, None))[0]
    if lang_name is None:
        return None

    boundary_types = _AST_BOUNDARY_NODE_TYPES.get(lang_name, set())
    if not boundary_types:
        return None

    try:
        tree = parser.parse(text.encode("utf-8"))  # type: ignore
    except Exception:
        return None

    # Collect top-level semantic nodes
    segments: list[str] = []

    def collect_nodes(node: object, depth: int = 0) -> None:
        """Recursively collect semantic boundary nodes."""
        node_type = getattr(node, "type", "")
        if node_type in boundary_types:
            start_byte = getattr(node, "start_byte", 0)
            end_byte = getattr(node, "end_byte", len(text))
            segment_text = text[start_byte:end_byte].strip()
            if segment_text:
                segments.append(segment_text)
            return  # Don't recurse into nested definitions to avoid duplication

        # For module/program root, recurse into children
        children = getattr(node, "children", [])
        for child in children:
            collect_nodes(child, depth + 1)

    root = getattr(tree, "root_node", None)
    if root is None:
        return None

    collect_nodes(root)

    if not segments:
        return None

    # Merge small segments or split oversized ones
    chunks: list[str] = []
    buffer: list[str] = []
    buffer_words = 0
    max_words = max(chunk_size_words, MIN_CHUNK_WORDS)

    for segment in segments:
        seg_words = len(segment.split())
        if seg_words > max_words * 2:
            # Flush buffer first
            if buffer:
                chunks.append("\n\n".join(buffer))
                buffer, buffer_words = [], 0
            # Split oversized segment with plain chunker (no overlap for code)
            sub_chunks = chunk_text(segment, chunk_size_words, overlap_words=0)
            chunks.extend(sub_chunks)
        elif buffer_words + seg_words > max_words and buffer:
            chunks.append("\n\n".join(buffer))
            buffer, buffer_words = [segment], seg_words
        else:
            buffer.append(segment)
            buffer_words += seg_words

    if buffer:
        chunks.append("\n\n".join(buffer))

    return [c for c in chunks if c.strip()]


def extract_imports(text: str, source: str) -> list[str]:
    """Extract import/require statements from source code."""
    ext = Path(source).suffix.lower()
    pattern = _IMPORT_PATTERNS.get(ext)
    if pattern is None:
        return []

    imports: list[str] = []
    for match in pattern.finditer(text):
        for group in match.groups():
            if group:
                imports.append(group.strip())
    return imports


def extract_function_calls(text: str) -> list[str]:
    """Extract function/method call names from code text."""
    # Filter out common keywords and built-ins
    keywords = {
        "if",
        "else",
        "for",
        "while",
        "return",
        "function",
        "def",
        "class",
        "import",
        "from",
        "try",
        "except",
        "catch",
        "finally",
        "with",
        "as",
        "print",
        "len",
        "str",
        "int",
        "float",
        "list",
        "dict",
        "set",
        "tuple",
        "True",
        "False",
        "None",
        "self",
        "this",
        "new",
        "const",
        "let",
        "var",
    }
    calls = []
    for match in _FUNCTION_CALL_PATTERN.finditer(text):
        name = match.group(1)
        if name not in keywords and not name.startswith("_"):
            calls.append(name)
    return list(set(calls))  # Deduplicate


# ---------------------------------------------------------------------------
# Rust acceleration — drop-in replacements when token_reducer_core is built.
# Falls back to pure-Python above when the extension is not installed.
# ---------------------------------------------------------------------------
try:
    import token_reducer_core as _rc  # type: ignore

    estimate_tokens = _rc.estimate_tokens
    tokenize = _rc.tokenize
    char_ngrams = _rc.char_ngrams
    chunk_text = _rc.chunk_text
except ImportError:
    pass


def resolve_import_to_file(
    import_path: str, source_file: str, indexed_files: set[str]
) -> str | None:
    """Attempt to resolve an import path to an actual indexed file."""
    source_dir = Path(source_file).parent
    dotted_import_as_path = import_path.replace(".", "/")

    # Common resolution strategies
    candidates = [
        # Relative import
        str(source_dir / f"{import_path}.py"),
        str(source_dir / f"{import_path}.ts"),
        str(source_dir / f"{import_path}.js"),
        str(source_dir / import_path / "__init__.py"),
        str(source_dir / import_path / "index.ts"),
        str(source_dir / import_path / "index.js"),
        # Convert dot notation to path
        str(source_dir / f"{dotted_import_as_path}.py"),
        str(source_dir / f"{dotted_import_as_path}.ts"),
    ]

    for candidate in candidates:
        normalized = str(Path(candidate).resolve())
        if normalized in indexed_files:
            return normalized

    return None
